// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCygPv5ZqkUPhRtGA8ugIqpPeoRJ1OJG2M',
    appId: '1:556644836322:web:323e79992fda6ae0718fbb',
    messagingSenderId: '556644836322',
    projectId: 'wedding-app-93de2',
    authDomain: 'wedding-app-93de2.firebaseapp.com',
    storageBucket: 'wedding-app-93de2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnKM46vJQqN-ahpJwbyx_OSHgq5WzfpYI',
    appId: '1:556644836322:android:b15785128d9c0031718fbb',
    messagingSenderId: '556644836322',
    projectId: 'wedding-app-93de2',
    storageBucket: 'wedding-app-93de2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbSg4euTGHBoNuHxBoZ3H9xr85FoR7PoU',
    appId: '1:556644836322:ios:443d5d12b4fa433c718fbb',
    messagingSenderId: '556644836322',
    projectId: 'wedding-app-93de2',
    storageBucket: 'wedding-app-93de2.appspot.com',
    iosBundleId: 'com.example.wedding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbSg4euTGHBoNuHxBoZ3H9xr85FoR7PoU',
    appId: '1:556644836322:ios:5c423a92c185658b718fbb',
    messagingSenderId: '556644836322',
    projectId: 'wedding-app-93de2',
    storageBucket: 'wedding-app-93de2.appspot.com',
    iosBundleId: 'com.example.wedding.RunnerTests',
  );
}
